export let psi = [
    {
      id: 4001,
      rodBroj: "HR00000",
      imePsa: "Odelia Victorian Paradise",
      spol: "F",
      boja: "tricolour",
      datumStenjenja: "2017-06-17",
      imeUzgajivacnice: "Victorian Paradise",
      imeUzgajivaca: "Petar Ferber",
      imeVlasnika: "Petar Ferber",
      pedigree:{
          majka:"majka",
          otac:"otac",
          bakaMajka:"bakaMajka",
          djedMajka:"djedMajka",
          bakaOtac:"bakaOtac",
          djedOtac:"djedOtac",
          prabakaBakaMajka:"prabakaBakaMajka",
          pradjedBakaMajka:"pradjedBakaMajka",
          prabakaDjedMajka:"prabakaDjedMajka",
          pradjedDjedMajka:"pradjedDjedMajka",
          prabakaBakaOtac:"prabakaBakaOtac",
          pradjedBakaOtac:"pradjedBakaOtac",
          prabakaDjedOtac:"prabakaDjedOtac",
          pradjedDjedOtac:"pradjedDjedOtac",
          praprabakaPrabakaBakaMajka:"praprabakaPrabakaBakaMajka",
          prapradjedPrabakaBakaMajka:"prapradjedPrabakaBakaMajka",
          praprabakaPradjedBakaMajka:"praprabakaPradjedBakaMajka",
          prapradjedPradjedBakaMajka:"prapradjedPradjedBakaMajka",
          praprabakaPrabakaDjedMajka:"praprabakaPrabakaDjedMajka",
          prapradjedPrabakaDjedMajka:"prapradjedPrabakaDjedMajka",
          praprabakaPradjedDjedMajka:"praprabakaPradjedDjedMajka",
          prapradjedPradjedDjedMajka:"prapradjedPradjedDjedMajka",     
          praprabakaPrabakaBakaOtac:"praprabakaPrabakaBakaOtac",
          prapradjedPrabakaBakaOtac:"prapradjedPrabakaBakaOtac",
          praprabakaPradjedBakaOtac:"praprabakaPradjedBakaOtac",
          prapradjedPradjedBakaOtac:"prapradjedPradjedBakaOtac",
          praprabakaPrabakaDjedOtac:"praprabakaPrabakaDjedOtac",
          prapradjedPrabakaDjedOtac:"prapradjedPrabakaDjedOtac",
          praprabakaPradjedDjedOtac:"praprabakaPradjedDjedOtac",
          prapradjedPradjedDjedOtac:"prapradjedPradjedDjedOtac"
      }
    },
  ];
  export default psi;
  